config/routes.rb
CommonCycling::Application.routes.draw do
  get "registers/home"
  root to: "registers#index"

  resources :registers 
  devise_for :users

  

end

app/models/register.rb
class Register < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
#paperclip
         has_attached_file :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  #before_filter :authenticate_user!
 

 def index
#    render text: params[:post].inspect
@list = Register.all
#render 'home' 
  end

# this is linking to station HOME page

def home
 
end


 def new
  
 end  

 def show
      @post = Register.find(params[:id])
end



def create
	# render text: params[:registers].inspect

 @post = Register.new(post_params)
  @post.save
  redirect_to @post
end
 
private
  def post_params
    params.require(:post_object).permit(:firstName, :middlename ,:lastname ,:bike_no ,
    	            :bike_company , :bike_model)	
end 

 
 




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<!--
   :title is  provided from each view using :provide function
 -->
  <title> Register your mountain bike | <%= yield(:title) %></title>
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>

   <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Registration", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home", registers_home_path %></li>
              <li><%= link_to "New Registration",    new_register_path %></li>
              <li><%= link_to "List all ", registers_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">

<!--   
  yield method inserts contents of each view page into site layout
-->
<%= yield %>
	
</body>
</html>

app/views/registers/home.html.erb
<% provide(:title, 'Home') %>
<!DOCTYPE html>


 <% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>


ls.org/' %>

<html>
  <body>
    <div class="center hero-unit">
    <h1> <%= t(:title) %> </h1>
    <h1> <%= l Date.today,format: :default %> </h1>
    <h2>
    <p>
      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </p>
  </h2>

 <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

 <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org' %>

  </body>
</html>

app/views/registers/index.html.erb
<h1>List of registerd bikes</h1>

 <% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

 

<table id="registers">
<thead>
  <tr>
    <th>FirstName</th>
    <th>Middle name</th>
    <th>Last name</th>
    <th>Bike Company</th>
    <th>Bike Model</th>
    <th>Bike No.</th>

  </tr>
</thead>
<tbody>
  <% @list.each do |post| %>
    <tr>
      <td><%= link_to(post.firstName, post) %></td>
      <td><%= post.middlename %></td>
      <td><%= post.lastname %></td>
      <td><%= post.bike_company %></td>
      <td><%= post.bike_model %></td>
      <td><%= post.bike_no %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/registers/new.html.erb
<h1>Register your  Bike</h1>
<p>Please fill in following fields to register your bike</p>

<!--
  use provide to set title at each view - this will be used by layouts/application.html.erb
-->
<% provide(:title, 'New Registration') %>


<!-- when a form is submitted, the fields of the form are sent to Rails as parameters. These parameters can then be referenced inside the controller actions 
:post_object can be accessed from action controller
-->

  <%= semantic_form_for :post_object, url: registers_path do |f| %>
    <%= f.input :firstName , :label => "First Name" %>
    <%= f.input :middlename , :required => false %>
    <%= f.input :lastName %>
    <%= f.input :bike_no %>
    <%= f.input :bike_company, :as => :select, :collection => ["Commencal" ,"Giant" ,"Trek" ,"Other"] %>
    <%= f.input :bike_model, :required => false, :hint => "Example: Commencal, Giant, Trek" %>
    <%= f.label :photo , "Photo"%>
    <%= f.file_field :photo %>
    <%= f.action :submit, :label => "Submit" , :button_html => { :value => 'Submit' ,:class => "lagoon" }  %>
  <% end %>



  <!--	<%= link_to "new", new_register_path %>
  	<%= link_to "All", registers_path %>
  -->

app/views/registers/show.html.erb
<p>
  <strong>Owner Name:</strong>
  <%= @post.firstName %>  <%= @post.middlename %> <%= @post.lastname %> 

</p>


<p>
  <strong>Bike Company</strong>
  <%= @post.bike_company %>
</p>

<p>
<strong>Bike model:</strong>
  <%= @post.bike_model %>
</p>
 

<p>
<strong>Bike No:</strong>
  <%= @post.bike_no %>
</p>
 